Support both MacOS and Win/Linux mktemp

diff --git a/bin/tempfile b/bin/tempfile
--- a/bin/tempfile
+++ b/bin/tempfile
@@ -1,14 +1,20 @@
 #!/usr/bin/env bash
 
 set -e
+set -x
 
 EXT=${1-.txt}
 
-# Mac OS's mktemp would not let append a file extension (Xs would not be
-# replaced), so we have to hack around that by running `mktemp` twice:
-#
-# https://stackoverflow.com/a/44510605/348524
-TMP_FILE=$(mktemp ${TMPDIR-/tmp}/message.XXXXXX)
-TMP_FILE_WITH_EXT=$(mktemp "${TMP_FILE}${EXT}")
-rm ${TMP_FILE}
+OS_MAC=$(uname -s | grep Darwin || :) # '|| :' swallows grep exit code
+if [[ -z $OS_MAC ]]; then
+    TMP_FILE_WITH_EXT=$(mktemp "${TMPDIR-/tmp}/message.XXXXXX${EXT}")
+else
+    # Mac OS's mktemp would not let append a file extension (Xs would not be
+    # replaced), so we have to hack around that by running `mktemp` twice:
+    #
+    # https://stackoverflow.com/a/44510605/348524
+    TMP_FILE=$(mktemp ${TMPDIR-/tmp}/message.XXXXXX)
+    TMP_FILE_WITH_EXT=$(mktemp "${TMP_FILE}${EXT}")
+    rm ${TMP_FILE}
+fi
 echo ${TMP_FILE_WITH_EXT}
